---
kind: pipeline
name: checks

trigger:
  event:
    exclude:
      - pull_request

steps:
- name: checks
  image: picons/picons
  pull: always
  commands:
    - ./resources/tools/check-index.sh ./build-source srp
    - ./resources/tools/check-index.sh ./build-source snp
    - ./resources/tools/check-logos.sh ./build-source/logos

---
kind: pipeline
name: snp-100x60

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh snp-full 100x60

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-snp-full/*

---
kind: pipeline
name: srp-100x60

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh srp-full 100x60

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-srp-full/*

---
kind: pipeline
name: snp-220x132

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh snp-full 220x132

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-snp-full/*

---
kind: pipeline
name: srp-220x132

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh srp-full 220x132

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-srp-full/*

---
kind: pipeline
name: snp-256x256

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh snp-full 256x256

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-snp-full/*

---
kind: pipeline
name: srp-256x256

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh srp-full 256x256

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-srp-full/*

---
kind: pipeline
name: snp-400x170

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh snp-full 400x170

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-snp-full/*

---
kind: pipeline
name: srp-400x170

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh srp-full 400x170

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-srp-full/*

---
kind: pipeline
name: snp-400x240

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh snp-full 400x240

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-snp-full/*

---
kind: pipeline
name: srp-400x240

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh srp-full 400x240

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-srp-full/*

---
kind: pipeline
name: snp-800x450

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh snp-full 800x450

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-snp-full/*

---
kind: pipeline
name: srp-800x450

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh srp-full 800x450

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-srp-full/*
